export enum GeneralVariables {
	full_name_of_the_educational_institution = "full_name_of_the_educational_institution",
	type_of_educational_institution = "type_of_educational_institution",
	legal_address = "legal_address",
	actual_address = "actual_address",
	director_manager__full_name = "director_manager__full_name",
	director_manager__phone = "director_manager__phone",
	deputy_director_for_academic_affairs__full_name = "deputy_director_for_academic_affairs__full_name",
	deputy_director_for_academic_affairs__phone = "deputy_director_for_academic_affairs__phone",
	deputy_director_for_educational_work__full_name = "deputy_director_for_educational_work__full_name",
	deputy_director_for_educational_work__phone = "deputy_director_for_educational_work__phone",
	responsible_employees_for_measures_to_prevent_child_injuries__first__job_title = "responsible_employees_for_measures_to_prevent_child_injuries__first__job_title",
	responsible_employees_for_measures_to_prevent_child_injuries__first__full_name = "responsible_employees_for_measures_to_prevent_child_injuries__first__full_name",
	responsible_employees_for_measures_to_prevent_child_injuries__first__phone = "responsible_employees_for_measures_to_prevent_child_injuries__first__phone",
	responsible_employees_for_measures_to_prevent_child_injuries__second__job_title = "responsible_employees_for_measures_to_prevent_child_injuries__second__job_title",
	responsible_employees_for_measures_to_prevent_child_injuries__second__full_name = "responsible_employees_for_measures_to_prevent_child_injuries__second__full_name",
	responsible_employees_for_measures_to_prevent_child_injuries__second__phone = "responsible_employees_for_measures_to_prevent_child_injuries__second__phone",

	responsible_from_the_department_of_internal_affairs__first__job_title = "responsible_from_the_department_of_internal_affairs__first__job_title",
	responsible_from_the_department_of_internal_affairs__first__full_name = "responsible_from_the_department_of_internal_affairs__first__full_name",
	responsible_from_the_department_of_internal_affairs__second__job_title = "responsible_from_the_department_of_internal_affairs__second__job_title",
	responsible_from_the_department_of_internal_affairs__second__full_name = "responsible_from_the_department_of_internal_affairs__second__full_name",
	responsible_from_the_department_of_internal_affairs__phones = "responsible_from_the_department_of_internal_affairs__phones",

	the_head_or_responsible_employee_of_the_road_maintenance_organization_that_carries_out_the_maintenance_of_the_road_network__full_name = "the_head_or_responsible_employee_of_the_road_maintenance_organization_that_carries_out_the_maintenance_of_the_road_network__full_name",
	the_head_or_responsible_employee_of_the_road_maintenance_organization_that_carries_out_the_maintenance_of_the_road_network__phone = "the_head_or_responsible_employee_of_the_road_maintenance_organization_that_carries_out_the_maintenance_of_the_road_network__phone",

	the_head_or_responsible_employee_of_a_road_maintenance_organization_that_carries_out_the_maintenance_of_technical_means_of_traffic_management__full_name = "the_head_or_responsible_employee_of_a_road_maintenance_organization_that_carries_out_the_maintenance_of_technical_means_of_traffic_management__full_name",
	the_head_or_responsible_employee_of_a_road_maintenance_organization_that_carries_out_the_maintenance_of_technical_means_of_traffic_management__phone = "the_head_or_responsible_employee_of_a_road_maintenance_organization_that_carries_out_the_maintenance_of_technical_means_of_traffic_management__phone",

	number_of_students_students_pupils = "number_of_students_students_pupils",
	availability_of_a_corner_for_bdd = "availability_of_a_corner_for_bdd",
	availability_of_a_bdd_cabinet = "availability_of_a_bdd_cabinet",
	availability_of_a_bdd_center = "availability_of_a_bdd_center",
	the_presence_of_a_motor_city_or_a_parking_lot_according_to_the_bdd = "the_presence_of_a_motor_city_or_a_parking_lot_according_to_the_bdd",
	the_presence_of_the_yid_squad = "the_presence_of_the_yid_squad",
	head_of_the_yid_squad__job_title = "head_of_the_yid_squad__job_title",
	head_of_the_yid_squad__full_name = "head_of_the_yid_squad__full_name",
	head_of_the_yid_squad__phone = "head_of_the_yid_squad__phone",
	the_presence_and_condition_of_the_fencing_of_the_territory_locking_devices_and_barriers = "the_presence_and_condition_of_the_fencing_of_the_territory_locking_devices_and_barriers",
	availability_of_a_school_bus_in_an_educational_institution = "availability_of_a_school_bus_in_an_educational_institution",

	// Время занятий в учреждении образования
	class_time_1st_shift__start_hour = "class_time_1st_shift__start_hour",
	class_time_1st_shift__start_minute = "class_time_1st_shift__start_minute",
	class_time_1st_shift__end_hour = "class_time_1st_shift__end_hour",
	class_time_1st_shift__end_minute = "class_time_1st_shift__end_minute",

	class_time_2nd_shift__start_hour = "class_time_2nd_shift__start_hour",
	class_time_2nd_shift__start_minute = "class_time_2nd_shift__start_minute",
	class_time_2nd_shift__end_hour = "class_time_2nd_shift__end_hour",
	class_time_2nd_shift__end_minute = "class_time_2nd_shift__end_minute",

	time_extracurricular_activities__start_hour = "time_extracurricular_activities__start_hour",
	time_extracurricular_activities__start_minute = "time_extracurricular_activities__start_minute",
	time_extracurricular_activities__end_hour = "time_extracurricular_activities__end_hour",
	time_extracurricular_activities__end_minute = "time_extracurricular_activities__end_minute",

	working_hours_on_the_sixth_school_day__start_hour = "working_hours_on_the_sixth_school_day__start_hour",
	working_hours_on_the_sixth_school_day__start_minute = "working_hours_on_the_sixth_school_day__start_minute",
	working_hours_on_the_sixth_school_day__end_hour = "working_hours_on_the_sixth_school_day__end_hour",
	working_hours_on_the_sixth_school_day__end_minute = "working_hours_on_the_sixth_school_day__end_minute"
}
