export enum VehicleVariables {
	brand = "brand",
	model = "model",
	registration_mark = "registration_mark",
	year_of_release = "year_of_release",
	number_of_passenger_seats = "number_of_passenger_seats",
	compliance_of_the_design_with_the_requirements_for_school_buses = "compliance_of_the_design_with_the_requirements_for_school_buses",

	// 2. Сведения о водителе(ях) автобуса(ов)
	first_bus_driver__full_name = "first_bus_driver__full_name",
	first_bus_driver__age = "first_bus_driver__age",
	first_bus_driver__date_of_employment = "first_bus_driver__date_of_employment",
	first_bus_driver__driving_experience_of_a_category_d_vehicle = "first_bus_driver__driving_experience_of_a_category_d_vehicle",
	first_bus_driver__date_of_the_upcoming_medical_examination = "first_bus_driver__date_of_the_upcoming_medical_examination",
	first_bus_driver__traffic_violations_committed = "first_bus_driver__traffic_violations_committed",

	second_bus_driver__full_name = "second_bus_driver__full_name",
	second_bus_driver__age = "second_bus_driver__age",
	second_bus_driver__date_of_employment = "second_bus_driver__date_of_employment",
	second_bus_driver__driving_experience_of_a_category_d_vehicle = "second_bus_driver__driving_experience_of_a_category_d_vehicle",
	second_bus_driver__date_of_the_upcoming_medical_examination = "second_bus_driver__date_of_the_upcoming_medical_examination",
	second_bus_driver__traffic_violations_committed = "second_bus_driver__traffic_violations_committed",

	// 3. Организационно-техническое обеспечение
	the_official_responsible_for_ensuring_road_safety_and_vehicle_operation__full_name = "the_official_responsible_for_ensuring_road_safety_and_vehicle_operation__full_name",
	the_official_responsible_for_ensuring_road_safety_and_vehicle_operation__date_of_appointment = "the_official_responsible_for_ensuring_road_safety_and_vehicle_operation__date_of_appointment",

	pre_trip_medical_examination__performs = "pre_trip_medical_examination__performs",
	pre_trip_medical_examination__on_the_basis_of = "pre_trip_medical_examination__on_the_basis_of",
	pre_trip_medical_examination__valid_until = "pre_trip_medical_examination__valid_until",

	control_over_the_technical_condition_and_design_of_the_vehicle__performs = "control_over_the_technical_condition_and_design_of_the_vehicle__performs",
	control_over_the_technical_condition_and_design_of_the_vehicle__on_the_basis_of = "control_over_the_technical_condition_and_design_of_the_vehicle__on_the_basis_of",
	control_over_the_technical_condition_and_design_of_the_vehicle__valid_until = "control_over_the_technical_condition_and_design_of_the_vehicle__valid_until",

	date_of_the_next_state_inspection = "date_of_the_next_state_inspection",

	bus_parking_place_during_nonworking_hours = "bus_parking_place_during_nonworking_hours",
	measures_to_prevent_unauthorized_use = "measures_to_prevent_unauthorized_use",

	// 4. Сведения о владельце автобуса
	bus_owner__legal_address = "bus_owner__legal_address",
	bus_owner__actual_address = "bus_owner__actual_address",
	bus_owner__phone_of_responsible_person = "bus_owner__phone_of_responsible_person"
}
